//! KV cache: the tier that decides whether two models fit on a phone.
//!
//! A conversation's key/value cache grows with every token and is worth keeping
//! — recomputing it means running the whole prefix through the model again. It
//! is also the largest, fastest-growing thing in memory once more than one
//! session is live, and on a 12 GB device it is what runs out first.
//!
//! So it is managed here rather than inside whichever process happens to be
//! doing inference. Three properties follow from that, and none of them are
//! available to a library that allocates from its own heap:
//!
//! - **It is evictable.** Under pressure a block is dropped, and the session
//!   carries on — slower, because it has to be fetched back, but correct.
//! - **It is spillable.** A dropped block is written to flash first, because
//!   unlike model weights it cannot be regenerated by re-reading a file. This
//!   is the one difference from the model store that matters.
//! - **Not all of it is worth the same.** A conversation's prefix is re-read on
//!   every turn; its middle usually is not. Evicting by recency alone throws
//!   away the prefix of an idle session and keeps the middle of a busy one,
//!   which is precisely backwards.
//!
//! The policy below scores a block on both, and the exit test checks that
//! prefixes survive while middles do not.

use crate::blk;
use crate::mm::{frames, phys_to_virt, PAGE_SIZE};
use crate::sync::SpinLock;
use crate::time;
use alloc::vec::Vec;
use core::sync::atomic::{AtomicU64, Ordering};

/// One block of cache. A page, which at a plausible 4 KiB per token-block is a
/// convenient unit for both the MMU and the disk.
pub const BLOCK_BYTES: usize = PAGE_SIZE;
const SECTORS_PER_BLOCK: u64 = (BLOCK_BYTES / blk::SECTOR_SIZE) as u64;

/// How much cache may be resident at once. Small on purpose: the interesting
/// behaviour is what happens when it is exceeded, and a budget nothing reaches
/// tests nothing.
pub const BUDGET_BLOCKS: usize = 64;

/// Blocks at or below this index are a conversation's prefix — the part a new
/// turn re-reads — and are the last thing worth evicting.
const PREFIX_BLOCKS: usize = 4;

#[derive(Clone, Copy, PartialEq, Eq)]
enum Block {
    /// In memory, at this physical frame.
    Resident { frame: usize, used_tick: u64 },
    /// Being written out right now. Writing goes out to a driver process and
    /// back, which means yielding — and a lock that masks interrupts cannot be
    /// held across a yield. So the block is marked, the lock is dropped, the
    /// I/O happens, and the lock is retaken to finish. A reader that finds one
    /// in this state waits.
    Spilling { frame: usize, sector: u64 },
    /// On flash, at this sector.
    Spilled { sector: u64 },
}

pub struct Session {
    pub id: u64,
    pub owner: usize,
    pub model: u64,
    blocks: Vec<Block>,
    pub created_tick: u64,
    pub last_tick: u64,
    pub hits: u64,
    pub spills: u64,
    pub restores: u64,
}

impl Session {
    pub fn blocks(&self) -> usize {
        self.blocks.len()
    }
    pub fn resident(&self) -> usize {
        self.blocks
            .iter()
            .filter(|b| matches!(b, Block::Resident { .. }))
            .count()
    }
    pub fn spilled(&self) -> usize {
        self.blocks.len() - self.resident()
    }
    /// How many of this session's prefix blocks are still in memory. The number
    /// the eviction policy exists to protect.
    pub fn prefix_resident(&self) -> usize {
        self.blocks
            .iter()
            .take(PREFIX_BLOCKS)
            .filter(|b| matches!(b, Block::Resident { .. }))
            .count()
    }
}

struct Cache {
    sessions: Vec<Session>,
    next_id: u64,
    resident_blocks: usize,
    /// Bump allocator over the filesystem's reserved spill region.
    spill_next: u64,
    spill_end: u64,
}

static CACHE: SpinLock<Cache> = SpinLock::new(Cache {
    sessions: Vec::new(),
    next_id: 1,
    resident_blocks: 0,
    spill_next: 0,
    spill_end: 0,
});

static EVICTIONS: AtomicU64 = AtomicU64::new(0);
static RESTORES: AtomicU64 = AtomicU64::new(0);
static PREFIX_EVICTIONS: AtomicU64 = AtomicU64::new(0);

/// Point the cache at the disk region the filesystem reserved for it.
pub fn init(spill_start: u64, spill_sectors: u64) {
    let mut c = CACHE.lock();
    c.spill_next = spill_start;
    c.spill_end = spill_start + spill_sectors;
}

/// What a block of session `s`, index `i` contains. Deterministic, so a block
/// that went to flash and came back can be checked rather than assumed.
pub fn pattern(session: u64, index: usize, offset: usize) -> u8 {
    (session
        .wrapping_mul(1103515245)
        .wrapping_add(index as u64 * 12345)
        .wrapping_add(offset as u64 * 31)
        >> 3) as u8
}

fn fill(frame: usize, session: u64, index: usize) {
    let p = phys_to_virt(frame) as *mut u8;
    for o in 0..BLOCK_BYTES {
        unsafe { core::ptr::write_volatile(p.add(o), pattern(session, index, o)) };
    }
}

pub fn open(owner: usize, model: u64) -> u64 {
    let mut c = CACHE.lock();
    let id = c.next_id;
    c.next_id += 1;
    let now = time::ticks();
    c.sessions.push(Session {
        id,
        owner,
        model,
        blocks: Vec::new(),
        created_tick: now,
        last_tick: now,
        hits: 0,
        spills: 0,
        restores: 0,
    });
    id
}

/// Score a block for eviction: higher means evict sooner.
///
/// Two terms. Age, so an idle session loses before a busy one. And position,
/// so a conversation's prefix is the last thing to go — it is re-read on every
/// turn, and evicting it means recomputing it every time.
fn eviction_score(index: usize, used_tick: u64, now: u64) -> u64 {
    let age = now.saturating_sub(used_tick);
    if index < PREFIX_BLOCKS {
        // Heavily discounted rather than pinned: under enough pressure a
        // prefix should still go, or the cache cannot shrink.
        age / 8
    } else {
        age + 1000
    }
}

/// Copy a block out to flash. No lock is held: this goes to a driver process.
fn write_out(frame: usize, sector: u64) -> bool {
    let src = phys_to_virt(frame) as *const u8;
    for s in 0..SECTORS_PER_BLOCK {
        let mut buf = [0u8; blk::SECTOR_SIZE];
        unsafe {
            core::ptr::copy_nonoverlapping(
                src.add(s as usize * blk::SECTOR_SIZE),
                buf.as_mut_ptr(),
                blk::SECTOR_SIZE,
            )
        };
        if blk::write_sector(sector + s, &buf).is_err() {
            return false;
        }
    }
    true
}

/// Spill blocks until `want` more will fit inside the budget.
///
/// Must be called with no lock held. Each eviction is three steps — choose
/// under the lock, write without it, finish under it again — because the write
/// yields and the lock masks interrupts.
fn make_room(want: usize) {
    loop {
        let now = time::ticks();
        let job = {
            let mut c = CACHE.lock();
            if c.resident_blocks + want <= BUDGET_BLOCKS {
                return;
            }
            // The worst block across every session.
            let mut victim: Option<(usize, usize, u64, usize)> = None;
            for (si, s) in c.sessions.iter().enumerate() {
                for (bi, b) in s.blocks.iter().enumerate() {
                    if let Block::Resident { frame, used_tick } = *b {
                        let score = eviction_score(bi, used_tick, now);
                        if victim.map_or(true, |(_, _, best, _)| score > best) {
                            victim = Some((si, bi, score, frame));
                        }
                    }
                }
            }
            let Some((si, bi, _, frame)) = victim else { return };
            if c.spill_next + SECTORS_PER_BLOCK > c.spill_end {
                return; // spill region full: nothing more can be evicted safely
            }
            let sector = c.spill_next;
            c.spill_next += SECTORS_PER_BLOCK;
            c.sessions[si].blocks[bi] = Block::Spilling { frame, sector };
            (si, bi, frame, sector)
        };

        let (si, bi, frame, sector) = job;
        // Unlike a weight page this cannot be regenerated by re-reading a file,
        // so it goes to flash before the frame does.
        let ok = write_out(frame, sector);

        let mut c = CACHE.lock();
        if ok {
            c.sessions[si].blocks[bi] = Block::Spilled { sector };
            c.sessions[si].spills += 1;
            c.resident_blocks -= 1;
            frames::free(frame);
            EVICTIONS.fetch_add(1, Ordering::Relaxed);
            if bi < PREFIX_BLOCKS {
                PREFIX_EVICTIONS.fetch_add(1, Ordering::Relaxed);
            }
        } else {
            // Put it back rather than lose it.
            c.sessions[si].blocks[bi] = Block::Resident { frame, used_tick: now };
            return;
        }
    }
}

/// Extend a session by `count` blocks, evicting to stay within budget.
pub fn append(id: u64, count: usize) -> Result<usize, &'static str> {
    let mut added = 0;
    for _ in 0..count {
        make_room(1);
        let mut c = CACHE.lock();
        if c.resident_blocks >= BUDGET_BLOCKS {
            return Err("cache is full and nothing could be evicted");
        }
        let Some(frame) = frames::alloc() else {
            return Err("out of memory");
        };
        let Some(s) = c.sessions.iter_mut().find(|s| s.id == id) else {
            frames::free(frame);
            return Err("no such session");
        };
        let index = s.blocks.len();
        let session_id = s.id;
        let now = time::ticks();
        s.blocks.push(Block::Resident { frame, used_tick: now });
        s.last_tick = now;
        c.resident_blocks += 1;
        drop(c);

        fill(frame, session_id, index);
        added += 1;
    }
    Ok(added)
}

/// Read a block, bringing it back from flash if it was spilled.
///
/// Returns whether it was already resident — the cache-hit signal the exit
/// test checks the policy against.
pub fn read(id: u64, index: usize, out: &mut [u8]) -> Result<bool, &'static str> {
    // A block being written out is neither in memory nor on flash yet. Wait
    // for whoever is spilling it rather than racing them.
    let state = loop {
        let now = time::ticks();
        let st = {
            let mut c = CACHE.lock();
            let s = c.sessions.iter_mut().find(|s| s.id == id).ok_or("no such session")?;
            s.last_tick = now;
            *s.blocks.get(index).ok_or("no such block")?
        };
        if let Block::Spilling { .. } = st {
            crate::sched::yield_now();
            continue;
        }
        break st;
    };
    let now = time::ticks();

    match state {
        Block::Resident { frame, .. } => {
            {
                let mut c = CACHE.lock();
                if let Some(s) = c.sessions.iter_mut().find(|s| s.id == id) {
                    s.hits += 1;
                    s.blocks[index] = Block::Resident { frame, used_tick: now };
                }
            }
            let src = phys_to_virt(frame) as *const u8;
            let n = out.len().min(BLOCK_BYTES);
            unsafe { core::ptr::copy_nonoverlapping(src, out.as_mut_ptr(), n) };
            Ok(true)
        }
        Block::Spilling { .. } => unreachable!("waited for the spill above"),
        Block::Spilled { sector } => {
            make_room(1);
            let Some(frame) = frames::alloc() else {
                return Err("out of memory restoring a block");
            };
            let dst = phys_to_virt(frame) as *mut u8;
            for s in 0..SECTORS_PER_BLOCK {
                let mut buf = [0u8; blk::SECTOR_SIZE];
                if blk::read_sector(sector + s, &mut buf).is_err() {
                    frames::free(frame);
                    return Err("could not read a spilled block back");
                }
                unsafe {
                    core::ptr::copy_nonoverlapping(
                        buf.as_ptr(),
                        dst.add(s as usize * blk::SECTOR_SIZE),
                        blk::SECTOR_SIZE,
                    )
                };
            }
            {
                let mut c = CACHE.lock();
                if let Some(s) = c.sessions.iter_mut().find(|s| s.id == id) {
                    s.blocks[index] = Block::Resident { frame, used_tick: now };
                    s.restores += 1;
                }
                c.resident_blocks += 1;
            }
            RESTORES.fetch_add(1, Ordering::Relaxed);
            let n = out.len().min(BLOCK_BYTES);
            unsafe { core::ptr::copy_nonoverlapping(dst, out.as_mut_ptr(), n) };
            Ok(false)
        }
    }
}

/// (id, blocks, resident, spilled, hits, spills, restores, prefix resident)
pub fn stat(id: u64) -> Option<(u64, usize, usize, usize, u64, u64, u64, usize)> {
    let c = CACHE.lock();
    let s = c.sessions.iter().find(|s| s.id == id)?;
    Some((
        s.id,
        s.blocks(),
        s.resident(),
        s.spilled(),
        s.hits,
        s.spills,
        s.restores,
        s.prefix_resident(),
    ))
}

pub fn for_each(mut f: impl FnMut(&Session)) {
    let c = CACHE.lock();
    for s in c.sessions.iter() {
        f(s);
    }
}

/// (resident blocks, budget, evictions, restores, prefix evictions)
pub fn totals() -> (usize, usize, u64, u64, u64) {
    let c = CACHE.lock();
    (
        c.resident_blocks,
        BUDGET_BLOCKS,
        EVICTIONS.load(Ordering::Relaxed),
        RESTORES.load(Ordering::Relaxed),
        PREFIX_EVICTIONS.load(Ordering::Relaxed),
    )
}
